thelook_analytics:
  outputs:
    dev:
      dataset: dbt_thelook
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: ucu-sandbox
      threads: 4
      type: bigquery
    prod:
      dataset: dbt_thelook_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: ucu-sandbox
      threads: 4
      type: bigquery
  target: dev
